'''
#Installation

source /home/project/11003581/Tools/miniforge3/bin/activate

conda create --prefix /home/project/11003581/conda-envs/scMultiomics python=3.7 r-base=4.2.1

conda activate /home/project/11003581/conda-envs/scMultiomics

## fixing R issue 
mkdir -p /home/project/11003581/R/library/4.2/
echo "R_LIBS_USER=/home/project/11003581/R/library/4.2/" >> ~/.Renviron
echo ".libPaths("/home/project/11003581/R/library/4.2/")" >> ~/.Rprofile

#or edit the Rprofile 
vim ~/.Rprofile
#add .libPaths("/home/project/11003581/R/library/4.2/")
#check
.libPaths()



install.packages("remotes")
install.packages("Seurat")
remotes::install_github("satijalab/azimuth", ref = "master")
install.packages("SeuratData")
remotes::install_github("10XGenomics/loupeR")


''' 
############# R scipt ###########

library (remotes)
library(Seurat)
library(Azimuth)
library(SeuratData)
library(loupeR)
loupeR::setup()

setwd(“/home/users/nus/ash.ps/scratch/mulitomics/celltype-annotation/”)

### Load datasets
data= Read10X_h5("/home/users/nus/ash.ps/scratch/mulitomics/analysis/10k_pbmc/outs/filtered_feature_bc_matrix.h5", use.names = TRUE, unique.features = TRUE)

# initialize a Seurat object of the data:
data<- CreateSeuratObject(data, project = "10k_PDMC", assay = "RNA")

#Run Azimuth (takes the feature barcode matrix and Seurat object reference as inputs)
Prediction<-RunAzimuth(data, "10k_PDMC")

#extract level 3 cell type annotations generated by Azimuth:
CellTypes_Azimuth<-Prediction@meta.data
CellTypes_Azimuth$Barcode<-rownames(CellTypes_Azimuth)
CellTypes_Azimuth$CustomLevel<-CellTypes_Azimuth$predicted.ann_level_3

#Assign barcodes with "Rare" labels in level 3 to more specific ones using the finest level of annotations provided by Azimuth:
iix<-which(CellTypes_Azimuth$predicted.ann_level_3=="Rare")
CellTypes_Azimuth$CustomLevel[iix]<-CellTypes_Azimuth$predicted.ann_finest_level[iix]

#Create output that can be added back into the Seurat object:
CellTypes_Azimuth<-CellTypes_Azimuth[,c("Barcode","CustomLevel")]
colnames(CellTypes_Azimuth)<-c("Barcode","CustomLevel")

#Add cell type annotations to the Seurat object as metadata:
rownames(CellTypes_Azimuth)<-CellTypes_Azimuth$Barcode
Prediction[["CustomLevel"]]<-CellTypes_Azimuth$Barcode[match(rownames(Prediction@meta.data), CellTypes_Azimuth$CustomLevel)]
Prediction<-AddMetaData(object = Prediction, metadata = CellTypes_Azimuth$CustomLevel, col.name = "CellTypes")

'''
## add disease metadata
diseasestate <- read.csv("/path/to/working/directory/diseasestate.csv")
rownames(diseasestate) <- diseasestate$Barcode #need to import csv with disease state assignments by barcode
Prediction[["DiseaseState"]] <- diseasestate$Barcode[match(rownames(Prediction@meta.data), diseasestate$disease.state)]
Prediction <- AddMetaData(object = Prediction, metadata = diseasestate$disease.state, col.name = "DiseaseState")
'''

tSNE_coordinates <- read.csv("t-SNE-Projection.csv", stringsAsFactors = F, header = T, row.names = 1)
tSNE_coordinates_mat <- as(tSNE_coordinates, "matrix")
Prediction[['tSNE']] <- CreateDimReducObject(embeddings = tSNE_coordinates_mat, key = "tSNE_", global = T, assay = "RNA")

#add back in is the sample ID information so that we do not lose track of which cell barcode came from which sample:
sampleID <- read.csv("SampleID.csv", stringsAsFactors = F, header = T, row.names = 1)
sampleID$Barcode<- rownames(sampleID)
Prediction[["sampleID"]] <- sampleID$Barcode[match(rownames(Prediction@meta.data), sampleID$SampleID)]
Prediction <- AddMetaData(object = Prediction, metadata = sampleID$SampleID, col.name = "sampleID")


#Run create_loupe_from_seurat command, which takes the Seurat object as input:
create_loupe_from_seurat(Prediction)

#write file
write.csv(CellTypes_Azimuth, "CellTypes_Azimuth.csv", row.names = FALSE)

########### Running the above R code as PBS job ##############

#!/bin/bash

#PBS -l select=2:ncpus=64:mem=128g
#PBS -l walltime=12:00:00
#PBS -P 11003581
#PBS -j oe
#PBS -N celltype_annotation


# Change to the directory where the job was submitted
cd $PBS_O_WORKDIR

conda activate /home/project/11003581/conda-envs/scMultiomics

# Run the R script
Rscript --vanilla celltype_annotation.R
